name: End-to-end tests
on:
  push:
    branches: 
      - 'master'
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Install CI
        run: npm ci
        
      - name: Cypress run
        run: npm run cy:open
