name: Build
on: 
  push:
    branches: 
      - 'master'
jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Cypress
        run: 
          npm ci
      
      - name: Run Cypress tests
        run: npm run test 
